version: '3.8'

services:
  namesrv:
    image: apache/rocketmq:4.8.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    restart: unless-stopped
    networks:
      - rocketmq
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:4.8.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - /home/zhuyiyi/docker-volume/rocketmq/conf/broker.conf:/home/rocketmq/rocketmq-4.8.0/conf/broker.conf
    depends_on:
      - namesrv
    restart: unless-stopped
    networks:
      - rocketmq
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.8.0/conf/broker.conf

networks:
  rocketmq:
    driver: bridge